media_folder: "/static/images/items"
public_folder: "/images/items"
site_url: "https://primordial-shop.netlify.app"
logo_url: "https://primordial-shop.netlify.app/logos/primordial-extended-nav.png"
show_preview_links: true
slug:
  encoding: "ascii"

backend:
  name: git-gateway
  branch: main
  repo: pprimodial/primordial-website

# local_backend: true

collections:
  - name: "items" 
    label: "Shop items" 
    format: "toml-frontmatter"
    folder: "/content/shop/"
    preview_path: "/shop/{{fields.slug}}"
    create: true
    slug: "{{fields.slug}}" 
    editor:
      preview: false
    fields: 
      - label: "Page title"
        name: "title"
        widget: "string"

      - label: "Description"
        name: "description"
        widget: "text"

      - label: "Url slug"
        name: "slug"
        widget: "string"

      - label: "Extra options"
        name: "extra"
        widget: "object"
        fields:
            - label: "Product Name"
              name: "name"
              widget: "string"

            - label: "This item is picked"
              name: "picked"
              widget: "boolean"

            - label: "Price of this product"
              name: "price"
              widget: "string"
              hint: "The price must also contain the unit. Eg: $300 (AUD), NPR 200 etc"

            - label: "Tags"
              name: "tags"
              widget: "list"
              defult: ["handmade"]
              min: 1
              max: 10
              hint: "Comma seperated tags that defined this product"

            - label: "Cover image"
              name: "cover_image"
              widget: "image"
              allow_multiple: false

            - label: "Product properties"
              name: "info"
              widget: "list"
              allow_add: true
              label_singular: "Add another property"
              fields:
                - label: "Product key"
                  name: "property_name"
                  widget: "string"
                  hint: "The name of property that will be shown in left side of product page. eg: color, size"
                - label: "Product value"
                  name: "property_value"
                  widget: "string"
                  hint: "The value of product key. Eg: if product key is color than product value may be red, green etc."
              default:
                - { property_name: "color", property_value: "" }
                - { property_name: "Item remaining", property_value: "1" }
